version: '3.8'

services:
  hl7-replicator:
    build: .
    container_name: hl7-replicator
    restart: unless-stopped
    ports:
      - "7001:7001"  # Order receiver (HIS -> ZenPACS)
      - "7002:7002"  # Report receiver (ZenPACS -> HIS)
      - "8080:8080"  # Web dashboard
    environment:
      # HL7 Listener Ports
      - ORDER_LISTEN_PORT=7001
      - REPORT_LISTEN_PORT=7002
      
      # ZenPACS endpoint (sabit)
      - ZENPACS_HL7_HOST=194.187.253.34
      - ZENPACS_HL7_PORT=2575
      
      # Hospital HIS endpoint (hastaneye göre değiştirilecek)
      - HOSPITAL_HIS_HOST=${HOSPITAL_HIS_HOST:-localhost}
      - HOSPITAL_HIS_PORT=${HOSPITAL_HIS_PORT:-7200}
      
      # Web dashboard
      - WEB_PORT=8080
      
      # Data storage
      - DB_PATH=/data
      
      # Logging
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
    networks:
      - hl7-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hl7-network:
    driver: bridge

volumes:
  hl7-data: